### ISSUE TITLE
Missing changelog on Github release

### ISSUE THREAD

**Issue by lachmanfrantisek** [user-cont/release-bot#130]
There is no changelog on GitHub releases.

e.g.: https://github.com/user-cont/conu/releases

**Comment by TomasTomecek** [comment]
Yes, latest stable release has this issue. The problem was, that if release bot failed while doing a release it would never upload the changelog. And while doing a rerun, the changelog is not updated.

I think I fixed it with:

https://github.com/user-cont/release-bot/commit/4c0b18dd1532b79d7459df57d03903b6a1b25d95#diff-a2053831ac76bc378a135c94c55b5125R333

**Comment by lachmanfrantisek** [comment]
@TomasTomecek so we can change this to `update-changelog-on-rerun`?

Otherwise, we can close this.

**Comment by jpopelka** [comment]
> When do we release?

We can try to do one (0.6.0 ?) at the DevConf workshop.

**Comment by TomasTomecek** [comment]
This should be fixed now, please reopen if it's not.
