### ISSUE TITLE
configuration, fedora: master should not be implied

### ISSUE THREAD

**Issue by TomasTomecek** [user-cont/release-bot#134]
It should be possible to release to epel only, e.g. so master (= rawhide) has to specified explicitly.

**Comment by CodHeK** [comment]
I was going through Fedora's Project ideas for GSoC'19 and found the "Release-bot" idea. I'd love to work on this project! Can you please suggest me how to proceed with this issue ?

**Comment by veer11997** [comment]
@TomasTomecek i would like to work on the project. And want to contribute on it.

**Comment by TomasTomecek** [comment]
Hi guys, thank you for your interest! We'd gladly accept your contributions.

Right now we are in a process of moving some of the release-bot's functionality into a dedicated project, https://github.com/packit-service/packit, as discussed in #138. This issue is affected by the move. I'm going close all the related issues so that it's not confusing.

**Comment by CodHeK** [comment]
Does this mean I should take up issues on the packit project ? If not then which issues should I try solving on this repo? 

On Thursday, March 7, 2019, 3:51 PM, Tomas Tomecek <notifications@github.com> wrote:


Hi guys, thank you for your interest! We'd gladly accept your contributions.

Right now we are in a process of moving some of the release-bot's functionality into a dedicated project, https://github.com/packit-service/packit, as discussed in #138. This issue is affected by the move. I'm going close all the related issues so that it's not confusing.

**Comment by TomasTomecek** [comment]
@CodHeK there is a ton of issues opened on this project, feel free to pick one or just comment if you need a better description and we'll improve it; I totally suggest running the bot locally yourself, so you'd get a good picture on what it does and how it can be improved; I don't suggest looking at packit since it's under heavy development and there are a ton of changes flowing every day.

We just had a planning session in our team and @rpitonak is going to (re)move the code from release-bot. The affected code does releasing to Fedora, we are planning for packit to take care of that.
