### ISSUE TITLE
refactor: stop passing self.new_release and self.new_pr dicts around

### ISSUE THREAD

**Issue by TomasTomecek** [user-cont/release-bot#187]
Release-bot uses two dicts to store data: new_release and new_pr. It's very cumbersome to work with them since one has no idea what's inside.

TODO

* [ ] remove ReleaseBot.{new_release,new_pr} dicts
* [ ] replace them with normal classes
* [ ] let methods and functions accept the parameters directly instead of a dict

**Comment by shresthagrawal** [comment]
@TomasTomecek Do you expect to create a different class for release and pr, or just have all the variables of the release and pr dicts in the existing class ?

**Comment by Aniket-Pradhan** [comment]
A `new_release` class will contain all the information from release-conf whereas `new_pr` will contain all the information for the PR.

Can I work on it?

**Comment by shresthagrawal** [comment]
@Aniket-Pradhan Sure! I will find something else.

**Comment by TomasTomecek** [comment]
my problem here is that I hate that we're passing a dict around because it's impossible to figure out what's inside

please suggest an improvement how the code look better and be easier to work with

**Comment by Aniket-Pradhan** [comment]
I was following your suggestion, that we can replace the dicts using classes. In that way, we would know what all is there inside the class.

The question arises, what should be the structure of the new classes. I went through the code, and I was able to summarize that:

`new_release` dict contains the following elements:

```
changelog
author_name
author_email
pypi
trigger_on_issue
labels
pr_id
commitish
version
```
`new_pr` contains:
```
version
issue_id
issue_number
labels
pr_url
previous_version
repo
```

I was thinking of creating two classes based on the above, and using them instead of the dicts. We can have methods to update these data items, or fetch them, or we can access them directly as well.

What's your say on this?

**Comment by TomasTomecek** [comment]
@Aniket-Pradhan sounds good, I like your suggestion.

**Comment by Aniket-Pradhan** [comment]
@TomasTomecek that's basically your suggestion. :stuck_out_tongue: 

Anyways, PR incoming!

**Comment by Aniket-Pradhan** [comment]
Time to close this. #192  :D
