### ISSUE TITLE
utils.py WARNING '' is not a valid version

### ISSUE THREAD

**Issue by jpopelka** [user-cont/release-bot#212]
I'm seeing this in logs of all deployed instances.
No idea where it comes from and whether it's a problem.

**Comment by Aniket-Pradhan** [comment]
In [utils.py](https://github.com/user-cont/release-bot/blob/master/release_bot/utils.py#L72). 

If the function is not able to parse a valid version, there is no reason to log the `version` variable (since it will be an empty string).

**Comment by jpopelka** [comment]
I see, the question is where/why it can't parse a version. Logging some more info in such case is definitely a good idea.

**Comment by Aniket-Pradhan** [comment]
What was the issue title in your case? We can start from there.

**Comment by jpopelka** [comment]
I don't know, but here's one such example - log from release-bot instance checking [conu repo](https://github.com/user-cont/conu):
https://paste.fedoraproject.org/paste/7rZeEgyXLjgZ05odFduwbw

**Comment by Aniket-Pradhan** [comment]
It's because one of the issues contain the word "release" and have no identifiable release version with it. 

In line [56](https://github.com/user-cont/release-bot/blob/master/release_bot/utils.py#L56) the bot looks for the word "release". If it finds the word in any of the issues, it looks for the version. And since no parsable version can be found it logs the warning.

**Comment by jpopelka** [comment]
Ok, I'd maybe lower the level from `warning` to `info` and log the `title`. What do you think? Interested in creating a PR?

**Comment by Aniket-Pradhan** [comment]
Sure. Why not! 

On it.
