### ISSUE TITLE
fedora keytab path is hardcoded in s2i script

### ISSUE THREAD

**Issue by TomasTomecek** [user-cont/release-bot#46]
https://github.com/user-cont/release-bot/blob/master/.s2i/bin/run#L3

This should probably be a placed inside repository configuration.

**Comment by jpopelka** [comment]
When building final image from s2i image, we [copy all files from private configuration repository](https://github.com/user-cont/release-bot/blob/master/.s2i/bin/assemble#L5) (i.e. conf.yaml, .pypirc and fedora.keytab) to $HOME and [run script points release-bot to it](https://github.com/user-cont/release-bot/blob/master/.s2i/bin/run#L20).

@TomasTomecek  are you suggesting that it should be configurable where assemble script puts the `fedora.keytab` ?
I don't see a use-case, can you draw some ?
thanks

**Comment by TomasTomecek** [comment]
My point is: if someone wants to use release bot just for PyPI, fedora.keytab is still needed. My expectation would be to write down path to the keytab in release-bot's config file and let the assemble script all the files. So the configuration to the keytab would be obtained from the config file, not via CLI.

No need to work on this, this should be just a low-prio RFE.

**Comment by jpopelka** [comment]
> if someone wants to use release bot just for PyPI, fedora.keytab is still needed.

Well, it's not actually.
If the `release-conf.yaml` in the to-be-released project repo says `fedora: false` the `fedora.keytab` is not accessed.

> My expectation would be to write down path to the keytab in release-bot's config file and let the assemble script all the files. So the configuration to the keytab would be obtained from the config file, not via CLI.

That's possible, but it's additional step for the user - to put some path into the config file.
And I might still be missing something, but I still don't see a benefit.

For now I think the easiest would be to change the `run` script so that it passes the `--keytab` to release-bot only if the `$HOME/fedora.keytab` exists (i.e. if the `assemble` script copied it from the secret config repo to the s2i image).
