### ISSUE TITLE
Don't pollute PR with comments if something gets wrong

### ISSUE THREAD

**Issue by jpopelka** [user-cont/release-bot#72]
It might happen that due to a bug or technical issue release-bot would be adding many comments to a PR. For example [here](https://github.com/user-cont/release-bot/pull/68#issuecomment-396304676) 2 same comments were added due to some Github outage (or some technical issue).
It'd be nice to have some mechanism to prevent this, like:
- don't add new comment if previous one is exactly the same
- don't add new comment if there already are (let's say) 5 comments from the bot

**Comment by TomasTomecek** [comment]
Maybe something like:
```
I am retrying a release %s and it fails with the same symptoms as my last try. Maintainer, please help me.
```

**Comment by fridex** [comment]
Might be helpful for you hopefully: In [Kebechet](https://github.com/thoth-station/kebechet) we incorporate git commit hash of the current master for which the issue is relevant. Before submitting a new comment, we just check that the master changed - assuming users are trying to fix hot issues and we also notify users with this that the issue is still relevant for changes being made to master. For [making bot silent](https://github.com/thoth-station/kebechet#suppressing-bot-verbosity), we check for "silent-bot" label on an issue/PR so we turn off comments completely if a user doesn't want to receive updates for long-living PRs/issues. [Here](https://github.com/thoth-station/user-api/issues/150) is an example our bot communicating on its own.

**Comment by TomasTomecek** [comment]
Actually github learned to group similar comments. I think we can close this.

**Comment by jpopelka** [comment]
> Actually github learned to group similar comments.

ah, nice

> I think we can close this.

+1
