### ISSUE TITLE
[Fedora] Wrong user & email in spec changelog

### ISSUE THREAD

**Issue by jpopelka** [user-cont/release-bot#89]
This is probably a deployment issue, not a bug, but:

```
  | 12:57:34.535 releasebot.py     INFO   I just released version 0.2.0 on PyPI
  | 12:57:34.535 releasebot.py     INFO   Triggering Fedora release
  | 12:57:36.478 utils.py          DEBUG  ['kinit', 'usercont@FEDORAPROJECT.ORG', '-k', '-t', '/opt/app-root/src/fedora.keytab']
  | 12:58:08.531 utils.py          DEBUG  ['fedpkg', 'clone', 'colin']
  | 12:58:08.537 utils.py          DEBUG  ['git', 'config', 'user.email', 'the.conu.bot@gmail.com']
  | 12:58:08.630 utils.py          DEBUG  ['git', 'config', 'user.name', 'Release bot']
  | 12:58:35.437 utils.py          DEBUG  ['fedpkg', 'switch-branch', 'master']
  | Switched to branch 'master'
  | 12:58:56.431 utils.py          DEBUG  ['fedpkg', 'sources']
  | Downloading colin-0.1.0.tar.gz
  | 12:59:20.833 utils.py          DEBUG  ['fedpkg', 'lint']
  | 0 packages and 1 specfiles checked; 0 errors, 0 warnings.
  | 12:59:22.740 utils.py          DEBUG  ['spectool', '-g', '/tmp/tmp3v59e3n6/colin/colin.spec']
  | Getting https://files.pythonhosted.org/packages/source/c/colin/colin-0.2.0.tar.gz  to ./colin-0.2.0.tar.gz
  | 12:59:47.031 utils.py          DEBUG  ['fedpkg', 'new-sources', 'colin-0.2.0.tar.gz']
  | Uploading: colin-0.2.0.tar.gz
  | Source upload succeeded. Don't forget to commit the sources file
  | 12:59:57.036 utils.py          DEBUG  ['fedpkg', 'commit', '-m', 'Update to 0.2.0']
  | [master 0e82dd1] Update to 0.2.0
  | 3 files changed, 7 insertions(+), 3 deletions(-)
  | 13:00:29.129 utils.py          DEBUG  ['fedpkg', 'push']
  | 13:00:29.129 fedora.py         DEBUG  Building branch 'master' in Fedora. It can take a long time.
  | 13:08:23.233 utils.py          DEBUG  ['fedpkg', 'build']
  | Building colin-0.2.0-1.fc30 for rawhide
  | Created task: 29764303
  | Task info: https://koji.fedoraproject.org/koji/taskinfo?taskID=29764303
```

If you check the changelog in [the build](https://koji.fedoraproject.org/koji/buildinfo?buildID=1145853) you'll see
```
* Wed Sep 19 2018 Jiri Popelka <jpopelka at redhat.com> 0.2.0-1
```
Not sure where's the spectool takes the author&email from, but it should be `usercont`, not me.

**Comment by TomasTomecek** [comment]
I think this is correct. AFAIK the logic is that author of the release is the person who created the 'new release issue'.

So the question is: should we put release bot name in there?

**Comment by lachmanfrantisek** [comment]
> who created the 'new release issue'

The issue was created by me... But the PR was merged by @jpopelka

**Comment by TomasTomecek** [comment]
Ah, okay :D 

Looking at the code, here's the method to get user credentials:
https://github.com/user-cont/release-bot/blob/1975538b6b420c83be6b7b7f68c92fafd28fde44/release_bot/github.py#L365
https://github.com/user-cont/release-bot/blob/master/release_bot/releasebot.py#L237

So is this really a misconfiguration? Or should we commit as the bot?

I actually vote for bot, since this dude is doing the hard work.

**Comment by kosciCZ** [comment]
The code responsible for this is here:

https://github.com/user-cont/release-bot/blob/ba3d9c16cf750891e4f6cec6e63c300a92b32536/release_bot/utils.py#L61

Where `author_name` is of the person who merged the release commit, because they're actually the one who should be responsible for the update, even if they're doing it through the bot, hence the entry in the changelog. Or such was the idea when this part of bot was written. 

Just to be clear, the bot is the commiter (info is fetched from github/defaults), the author of the change in changelog is person who merged the release PR.

I actually disagree with @TomasTomecek and think that bot gets enough recognition as a commiter and that the changelog entry should be easy to trace back to person who approved the release.

**Comment by jpopelka** [comment]
> Just to be clear, the bot is the commiter (info is fetched from github/defaults), the author of the change in changelog is person who merged the release PR.

OK, thanks for explanation, I didn't realize the bot is the git commiter.
Then I'm fine with as it is now.
