### ISSUE TITLE
Provide a support for COPR

### ISSUE THREAD

**Issue by phracek** [user-cont/release-bot#96]
It would be nice to provide a support into release-bot building packages via COPR.

I think it would be an option in conf.yaml file like `copr: true`.
For more information be in contact with @xsuchy.

**Comment by TomasTomecek** [comment]
Could you please provide more information on how you expect this to work?

Also, `copr: true` is not enough: the bot would need to know in which copr it should build, what targets, would also need credentials, etc.

Since github supports webhooks and copr has an API, this could be the way to go, that's why I would love to know your use case more.

**Comment by xsuchy** [comment]
Note that Copr can work with webhooks as well.
https://docs.pagure.org/copr.copr/user_documentation.html#github-webhooks
